refactor: move "get an import" from HTTP API to JS API
digidem/mapeo-map-server pull request #110
Opened 2024-01-27 16:44 UTC by EvanHahn

This moves the public "get an import" interface from HTTP to JavaScript. In other words, you won't make an HTTP GET to `/import/:importId` any more. Instead, you'll call `server.getImport(importId)`.

This is the first step in a larger refactor, where most of the interface will be moved from HTTP to JS. Because this is the first step, several changes have to be made:

- `createMapServer` returns a newly-created `MapServer` instance, rather than a `FastifyInstance`. This instance is the main public interface.
- `MapServer` takes on many of the responsibilities of `Api`, such as initializing the database and dealing with server shutdown.
- Tests need to work a bit differently. Those in the "new style" deal with the `MapServer` instance where those in the "old style" deal with the Fastify instance.
- Update documentation.

I suspect future moves, such as migrating `GET /styles`, will be much smaller patches.

BREAKING CHANGE: `GET /imports/:importId` replaced with `getImport()`

2024-01-27 16:49 UTC, EvanHahn commented on src/api/index.ts
> -function init(db: Database): Context {
This whole function was moved into `MapServer`.

2024-01-27 16:49 UTC, EvanHahn commented on src/api/index.ts
> -const ApiPlugin: FastifyPluginAsync<MapServerOptions> = async (
This plugin is no longer necessary.

2024-01-27 16:49 UTC, EvanHahn commented on src/api/index.ts
> -  fastify.addHook('onClose', async () => {
Instead of using a Fastify hook, this stuff is done in `MapServer.prototype.close`.

2024-01-27 16:49 UTC, EvanHahn commented on src/lib/imports.ts
> +import type { Database } from 'better-sqlite3'
This file used to have a bunch of runtime types which were used by the route. Now they're only compile-time types.

I also moved the documentation out of `API.md` into this file.

2024-01-27 16:49 UTC, EvanHahn commented on src/map-server.ts
> +    this.fastifyInstance.close()
All of this was moved from the `Api` Fastify on-close hook.

2024-01-27 16:49 UTC, EvanHahn commented on src/map-server.ts
> +}
All of this was moved from `Api`'s old setup.

2024-01-27 16:49 UTC, EvanHahn commented on src/map-server.ts
> +}
All of this was moved from the old creation of the Fastify server.

The main difference: `Api` is no longer a Fastify plugin so we just call `.decorate('api', api)`.

2024-02-12 18:03 UTC, achou11 requested changes

2024-02-12 18:03 UTC, achou11 commented on src/map-server.ts
correct me if this is about a smoother or more incremental migration, but would say that this class doesn't need to handle anything related to fastify (i.e. no need to create the fastify instance and use it). i'd even argue that this class shouldn't even be named `MapServer` anymore 😄 not sure what a better name would be (maybe `MapManager` since that's the feature in Mapeo that this powers?).

2024-02-12 18:08 UTC, achou11 commented on src/map-server.ts
i guess the one potential argument against what I just noted is that it may be needed in order to get fully qualified urls when resolving things like style definitions (e.g. urls that occupy fileds like `sources`, `glyphs`, etc). part of me is hoping that there's an elegant way of avoiding needing the server instance (maybe something more generic like a constructor opt called `getHttpUrlBase()`?)

2024-02-12 18:33 UTC, EvanHahn commented on src/map-server.ts
_tl;dr: I think we should keep `MapServer` until we completely remove the HTTP server._

I see the HTTP→JS migration in two parts:

1. Use JS for the API, but keep HTTP server functionality for things like tiles.
2. Completely remove the HTTP server.

I think `MapServer` still makes sense for part 1 and I think it should remain while we still have a server. I agree that it doesn't make sense in part 2, and that a rename like `MapManager` would work.

Does that seem reasonable for now?

2024-02-12 18:35 UTC, achou11 commented on src/map-server.ts
yeah makes sense! just wanted to highlight in case there were any additional changes that could be done in anticipation of (2) without compromising on (1)

2024-02-12 18:53 UTC, EvanHahn commented on src/map-server.ts
I don't think so yet, but (1) I might be wrong (2) I'll keep that in mind in any case!

2024-02-12 18:55 UTC, merged